services:
  app:
    build: .
    container_name: nest_app
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: db  # Se usa "db" dentro de Docker
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      HOST_API: http://app:${PORT}/api  # Se usa "app" en lugar de "localhost" dentro de Docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"  # Expone el puerto de la API
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:14.3
    container_name: nest_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
